language: python
python:
  - "3.4"
services:
  - redis-server
addons:
  postgresql: "9.3"
env: LUTHER_SETTINGS=$TRAVIS_BUILD_DIR/tests/travis/travis_config.py
before_install: 
    - bash tests/travis/travis_setup.sh
    - sudo apt-get install -y python3-psycopg2
    - pip install psycopg2
install: python setup.py build install
before_script: psql -c 'create database luther_test;' -U postgres
script: python tests/run_tests.py
after_failure:
    - sudo cat /var/log/syslog
after_success:
    - sudo cat /var/log/syslog
