language: python
python:
  - "3.4"
services:
  - redis-server
env: LUTHER_SETTINGS=$TRAVIS_BUILD_DIR/tests/travis/travis_config.py
before_install: bash tests/travis/travis_setup.sh
install: python setup.py build install
script: python tests/run_tests.py
after_failure:
    - sudo cat /var/log/syslog
after_success:
    - dig travis-example @127.0.0.1
    - dig travis-ip-example @127.0.0.1
    - sudo cat /var/log/syslog
